services:
  redis:
    container_name: redis
    image: "redis/redis-stack-server"
    ports:
      - "6379:6379"
  redis-insight:
    container_name: redis-insight
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"

#  ollama:
#    container_name: ollama
#    volumes:
#      - ollama:/root/.ollama
#    ports:
#      - "11434:11434"
#    tty: true
#    restart: unless-stopped
#    image: ollama/ollama:latest
#
#  ollama-pull:
#    image: docker/genai:ollama-pull
#    container_name: ollama-pull
#    environment:
#      - OLLAMA_BASE_URL=http://ollama:11434
#      - LLM=mistral
#
#volumes:
#  ollama: {}
#  open-webui: {}